### ISSUE TITLE
Reuse for php-pm?

### ISSUE THREAD

**Issue by andig** [phlib/console-process#4]
Dear maintainers, 

in https://github.com/php-pm/php-pm/pull/351 I've borrowed some code for use with php-pm, sources are attributed in code comments. php-pm is MIT license. Is this borrowing acceptable from your perspective?

Much appreciated, 
Andreas

**Comment by chrisminett** [comment]
Hi Andreas,

Thanks for asking, and glad you found it useful!

The LGPL licence we use means that any modifications to this package are allowed, but need to be open-sourced. It also means that this package can be used in a larger body of work, but that larger project **does not** need to be open-sourced. We think this most closely resembles the situation here.

This, plus the fact that you've attributed the methods back to this package mean it's fine with us!

I would possibly make a minor suggestion - in the URL you've used, link to the source file via a commit rather than a branch. The branch has potential to change (especially master which you've used), meaning the link will become obsolete.

Cheers,
ChrisM

**Comment by andig** [comment]
Excellent, much appreciated! Will update the links as requested.
